// Generated by OmO. Delete this file to stop loading the default global extension.
export { default } from "file:///Users/sungsoopark/Documents/GitHub/oh-my-openagent-7491/node_modules/.bun/@code-yeongyu+senpi@2026.9.3-3+6ef929de919b1675/node_modules/@code-yeongyu/senpi/dist/core/extensions/builtin/diff.js";
