// Generated by OmO. Delete this file to stop loading the default global extension.
export { default } from "file:///private/tmp/oh-my-openagent-7491-final/node_modules/.bun/@code-yeongyu+senpi@2026.9.4-3+bcafad38bfc859d1/node_modules/@code-yeongyu/senpi/dist/core/extensions/builtin/files.js";
